import { Inter } from "next/font/google";
import { ResetStyled } from "./css/StyledReset";
import { GlobalStyled } from "./css/StyledGlobal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ResetStyled />
        <GlobalStyled />
        {children}
      </body>
    </html>
  );
}
